// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string, disabled = false): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    if (disabled) {
      // Return a benign empty 200 response in disabled mode to avoid runtime errors.
      return Promise.resolve(new Response(null, { status: 200, statusText: 'OK' })) as any;
    }
    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function normalizeSupabaseUrl(url: string): string {
  // Strip trailing spaces
  let u = url.trim();
  // Remove any trailing slashes
  u = u.replace(/\/?$/, '');
  // If someone accidentally saved the REST or AUTH subpaths in the env, strip them
  u = u.replace(/\/(rest|auth)\/(v1|v2)(\/)?$/i, '');
  return u;
}

function makeNoopSupabaseClient() {
  const ok = { data: null, error: null } as const;
  const empty = Promise.resolve({ data: [] as any, error: null as any });
  const auth = {
    getSession: async () => ({ data: { session: null }, error: null } as const),
    getUser: async () => ({ data: { user: null }, error: null } as const),
    signInWithPassword: async () => ({ data: { user: null, session: null } as any, error: new Error('Supabase disabled') }),
    signUp: async () => ({ data: { user: null, session: null } as any, error: new Error('Supabase disabled') }),
    signInWithOAuth: async () => ({ data: { url: undefined } as any, error: new Error('Supabase disabled') }),
    signOut: async () => ok,
    exchangeCodeForSession: async () => ok,
    getSessionFromUrl: async () => ok,
    updateUser: async () => ({ data: { user: null }, error: new Error('Supabase disabled') }),
    onAuthStateChange: (_cb?: any) => ({ data: { subscription: { unsubscribe(){} } }, error: null } as any),
    getClaims: async () => ({ data: { claims: null } as any, error: new Error('Supabase disabled') }),
  } as any;
  const from = (_table: string) => ({
    select: () => empty,
    insert: () => Promise.resolve({ data: null, error: new Error('Supabase disabled') }),
    update: () => Promise.resolve({ data: null, error: new Error('Supabase disabled') }),
    delete: () => Promise.resolve({ data: null, error: new Error('Supabase disabled') }),
    eq: () => ({ select: () => empty, update: () => Promise.resolve({ data: null, error: new Error('Supabase disabled') }), delete: () => Promise.resolve({ data: null, error: new Error('Supabase disabled') }), order: () => empty, in: () => empty })
  });
  const rpc = async () => ({ data: null as any, error: new Error('Supabase disabled') });
  return { auth, from, rpc } as any;
}

function isValidHttpUrl(u?: string | null) {
  if (!u) return false;
  try {
    const url = new URL(u);
    return url.protocol === 'http:' || url.protocol === 'https:';
  } catch {
    return false;
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const RAW_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  // If env missing, return a no-op client that won't crash the UI
  const envMissing = !RAW_SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;
  const maybeUrl = RAW_SUPABASE_URL ? normalizeSupabaseUrl(RAW_SUPABASE_URL) : null;
  const hasValidUrl = isValidHttpUrl(maybeUrl);
  const disabled = envMissing || !hasValidUrl;

  if (disabled) {
    console.warn('[Supabase] Missing or invalid URL/key. Using no-op Supabase client.');
    // Fully avoid calling createClient when disabled
    return makeNoopSupabaseClient() as any;
  }

  return createClient<Database>(maybeUrl!, SUPABASE_PUBLISHABLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

