// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string, disabled = false): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    if (disabled) {
      // Return a benign empty 200 response in disabled mode to avoid runtime errors.
      return Promise.resolve(new Response(null, { status: 200, statusText: 'OK' })) as any;
    }
    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function normalizeSupabaseUrl(url: string): string {
  // Strip trailing spaces
  let u = url.trim();
  // Remove any trailing slashes
  u = u.replace(/\/?$/, '');
  // If someone accidentally saved the REST or AUTH subpaths in the env, strip them
  u = u.replace(/\/(rest|auth)\/(v1|v2)(\/)?$/i, '');
  return u;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const RAW_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  // If env missing, return a no-op client that won't crash the UI
  const envMissing = !RAW_SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;
  const SUPABASE_URL = RAW_SUPABASE_URL ? normalizeSupabaseUrl(RAW_SUPABASE_URL) : 'http://localhost-disabled';

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_disabled', {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_disabled', envMissing),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  if (envMissing) {
    console.warn('[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY not set. Running in disabled/no-op mode.');
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

